github:
- Ekisa02
patreon: qxboost
open_collective: qxboost
ko_fi: qxboost
buy_me_a_coffee: qxboost
# If you want to add custom external links, use a list:
custom:
- "https://example.com/donate"
- "https://opencollective.com/qxboost"
